name: gpt_smarthome
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - openjdk=17
  - maven
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic-settings
      - python-dotenv
      - numpy==1.26.4
      - scipy
      - sounddevice
      - soundfile
      - edge-tts
      - opencv-contrib-python==4.11.0.86
      - mediapipe==0.10.21
      - SpeechRecognition
      - openai
      - httpx
      - pyttsx3
      - pytest
